version: '3.3'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  api:
    image: fartem2003/food-backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/mediafiles/
      - ../data/:/app/data/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: fartem2003/foodgramfrontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - api
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/static/
      - media_value:/var/html/mediafiles/
    depends_on:
      - frontend
      - api

volumes:
  postgres_data:
  static_value:
  media_value:
  result_build:
