# Generated by Django 2.2.19 on 2022-03-12 10:20

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ингридиенты', max_length=256, verbose_name='Ингридиент')),
                ('measurement_unit', models.CharField(help_text='Единица измерения', max_length=20, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Ingredient_in_recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(default=0, help_text='Количество', verbose_name='Количество')),
                ('ingredient', models.ForeignKey(help_text='Ингридиент в рецепте', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='api.Ingredient', verbose_name='Ингридиент в рецепте')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=256, verbose_name='Название тега')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('slug', models.SlugField(help_text='Slug для тега', unique=True, verbose_name='Slug для тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рецепта', max_length=256, verbose_name='Название рецепта')),
                ('text', models.TextField(help_text='Описание', verbose_name='Описание')),
                ('cooking_time', models.SmallIntegerField(default=0, help_text='Общее время приготовления', verbose_name='Общее время приготовления')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingredients', models.ManyToManyField(help_text='Ингридиенты', related_name='recipe', to='api.Ingredient_in_recipe', verbose_name='Ингридиенты')),
                ('tags', models.ManyToManyField(help_text='Теги', related_name='recipe', to='api.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Pецепт',
                'verbose_name_plural': 'Pецепт',
            },
        ),
    ]
