# Generated by Django 2.2.19 on 2022-03-13 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(help_text='Ингридиенты', on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='api.Ingredient_in_recipe', verbose_name='Ингридиенты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Теги', related_name='recipe', to='api.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='ingredient_in_recipe',
            name='ingredient',
            field=models.ForeignKey(help_text='Ингридиент в рецепте', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='api.Ingredient', verbose_name='Ингридиент в рецепте'),
        ),
    ]
