# Generated by Django 2.2.19 on 2022-03-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220313_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ингридиенты', related_name='recipe', to='api.Ingredient_in_recipe', verbose_name='Ингридиенты'),
        ),
    ]
